// apps/web/app/login/page.tsx
'use client'

import { useState } from 'react'
import { useRouter } from 'next/navigation'
import { supabase, getUserRole } from '@snowpro/lib/supabase'

const ROLE_REDIRECTS = {
  admin: 'https://admin.snowpro.com',
  client: 'https://app.snowpro.com',
  crew: 'https://crew.snowpro.com',
}

export default function LoginPage() {
  const router = useRouter()
  const [email, setEmail] = useState('')
  const [password, setPassword] = useState('')
  const [error, setError] = useState<string | null>(null)
  const [loading, setLoading] = useState(false)

  async function handleLogin(e: React.FormEvent) {
    e.preventDefault()
    setError(null)
    setLoading(true)

    const { error: authError } = await supabase.auth.signInWithPassword({
      email,
      password,
    })

    if (authError) {
      setError(authError.message)
      setLoading(false)
      return
    }

    const role = await getUserRole()

    if (!role || !ROLE_REDIRECTS[role]) {
      setError('Account not configured. Contact support.')
      setLoading(false)
      return
    }

    window.location.href = ROLE_REDIRECTS[role]
  }

  return (
    <main>
      <form onSubmit={handleLogin}>
        <h1>Sign in to SnowPro</h1>
        {error && <p role="alert">{error}</p>}
        <input
          type="email"
          placeholder="Email"
          value={email}
          onChange={(e) => setEmail(e.target.value)}
          required
        />
        <input
          type="password"
          placeholder="Password"
          value={password}
          onChange={(e) => setPassword(e.target.value)}
          required
        />
        <button type="submit" disabled={loading}>
          {loading ? 'Signing in…' : 'Sign in'}
        </button>
      </form>
    </main>
  )
}

// apps/admin/app/pages/login.vue
<script setup lang="ts">
import { supabase } from '@snowpro/lib/supabase' // ← replaces useSupabaseClient()

const email = ref('')
const password = ref('')
const error = ref<string | null>(null)
const loading = ref(false)
const router = useRouter()

async function handleLogin() {
  error.value = null
  loading.value = true

  const { error: authError } = await supabase.auth.signInWithPassword({
    email: email.value,
    password: password.value,
  })

  if (authError) {
    error.value = authError.message
    loading.value = false
    return
  }

  const { data } = await supabase
    .from('profiles')
    .select('role')
    .eq('id', (await supabase.auth.getUser()).data.user?.id)
    .single()

  loading.value = false

  if (data?.role === 'admin') {
    router.push('/')
  } else {
    await supabase.auth.signOut()
    error.value = 'Access denied. Admin accounts only.'
  }
}
</script>

<template>
  <div>
    <h1>SnowPro Admin</h1>
    <p v-if="error" role="alert">{{ error }}</p>
    <input v-model="email" type="email" placeholder="Email" />
    <input v-model="password" type="password" placeholder="Password" />
    <button :disabled="loading" @click="handleLogin">
      {{ loading ? 'Signing in…' : 'Sign in' }}
    </button>
  </div>
</template>
